name: Release

on:
  workflow_dispatch:
  release:
    types: [created]

defaults:
  run:
    working-directory: SensorGUARD

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: set up a2p2
      run: wget -qO a2p2.zip https://extgit.iaik.tugraz.at/fdraschbacher/a2p2/-/raw/main/a2p2_distribution_v1.0.1.zip && unzip a2p2.zip -d a2p2 && rm a2p2.zip 
      working-directory: .

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew assemblePatchPackages

    - name: Get Current Release
      id: get_current_release
      uses: joutvhu/get-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.get_current_release.outputs.upload_url }}
        asset_path: SensorGUARD/app/build/outputs/patch/patch_static.zip
        asset_name: sensorguard_static.zip
        asset_content_type: application/zip
